model:
    arch: bhNet_HR
data:
    dataset: diydata
    train_split: train_aug
    val_split: val
    img_rows: 400
    img_cols: 'same'
    path: E:\Building_Height_Estimation\sample-BHNet-HR
    n_class: 1
    n_maxdisp: 192
training:
    epochs: 300
    batch_size: 4
    learning_rate: 0.001
    resume: ''
    device: 'cuda'
